import type { Metadata } from "next"
import LocalFont from "next/font/local"
import "./globals.css"
import { Header } from "@/components/header"
import { TopLoader } from "@/components/top-loader"
import { ApolloProvider } from "@/components/apollo-provider"

const radnika = LocalFont({
  src: "../public/radnikanext-medium.woff2",
  weight: "400",
  style: "normal",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${radnika.className} antialiased`}>
        <ApolloProvider>
          <TopLoader />

          <Header />

          <div className="container">{children}</div>
        </ApolloProvider>
      </body>
    </html>
  )
}
